name: Setup pnpm
description: Reduce boilerplate when installing setting up Node.js and installing pnpm dependencies.
author: Mark Skelton
branding:
  icon: play
  color: blue
inputs:
  flags:
    description: Additional flags to pass to the install command.
  pnpm-version:
    description: pnpm version to use, defaults to the current version.
    default: "8"
  node-version:
    description: Node version to use, defaults to the current LTS version.
    default: "20.x"
  ref:
    description: Git ref to checkout. Passed to `actions/checkout`.
  fetch-depth:
    description: Fetch depth of the checkout. Passed to `actions/checkout`.
  registry-url:
    description: Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm
    - name: Install pnpm dependencies
      shell: bash
      run: pnpm install ${{ inputs.flags }}
